USE outfit_db;

CREATE TABLE IF NOT EXISTS outfits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gender VARCHAR(30) NOT NULL,
    occasion VARCHAR(30) NOT NULL,
    weather VARCHAR(30) NOT NULL,
    style VARCHAR(30) NOT NULL,
    venue VARCHAR(30) NOT NULL,
    fit VARCHAR(30) NOT NULL,
    formality_level VARCHAR(30) NOT NULL,
    skin_tone VARCHAR(30) NOT NULL,
    topwear_type VARCHAR(30),
    topwear_neck_type VARCHAR(30),
    sleeve_type VARCHAR(30),
    topwear_pattern VARCHAR(30),
    topwear_fabric VARCHAR(30),
    topwear_color VARCHAR(30),
    bottomwear_type VARCHAR(30),
    bottomwear_length VARCHAR(30),
    bottomwear_pattern VARCHAR(30),
    bottomwear_fabric VARCHAR(30),
    bottomwear_color VARCHAR(30),
    footwear_type VARCHAR(30),
    footwear_color VARCHAR(30),
    one_piece_type VARCHAR(30),
    one_piece_length VARCHAR(30),
    one_piece_fabric VARCHAR(30),
    one_piece_color VARCHAR(30),
    one_piece_pattern VARCHAR(30),
    layering_type VARCHAR(30),
    layering_pattern VARCHAR(30),
    layering_fabric VARCHAR(30),
    layering_color VARCHAR(30),
    watch_type VARCHAR(30),
    watch_strap_type VARCHAR(30),
    watch_color VARCHAR(30),
    belt_material VARCHAR(30),
    belt_color VARCHAR(30),
    hat_type VARCHAR(30),
    cap_hat_color VARCHAR(30),
    neck_bow_tie VARCHAR(30),
    earrings VARCHAR(30),
    fragrance VARCHAR(30)
);
